name: Preview Deployment

on:
  pull_request:
    branches: [main, develop]

jobs:
  build-preview:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Package application (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: bun run pack

      - name: Package application (Windows)
        if: matrix.os == 'windows-latest'
        run: bun run pack

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-${{ matrix.os }}-${{ github.run_id }}
          path: |
            dist/*-1.0.0.*
            dist/make/**/*.*
          if-no-files-found: error
          retention-days: 7

      - name: Comment PR with build status
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview build completed for ${{ matrix.os }}!\n\n✅ Build artifacts are available for download (expires in 7 days)\n🔗 [Download ${{ matrix.os }} build](https://github.com/${{ context.repo.owner }}/${{ context.repo.repo }}/actions/runs/${{ github.run_id }})`
            })
